# Generated by Django 4.0.1 on 2022-01-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_review_movie_movie_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collection.cinema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='genres',
            field=models.ManyToManyField(to='collection.Genre'),
        ),
    ]
