# Generated by Django 4.0.1 on 2022-01-14 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_review_cinema_review_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='genres',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collection.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='cinema',
            field=models.CharField(max_length=100),
        ),
    ]
