# Generated by Django 4.0.1 on 2022-01-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_remove_movie_review_remove_review_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.AlterField(
            model_name='review',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.cinema'),
        ),
    ]
