# Generated by Django 4.0.1 on 2022-01-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_remove_review_movie_alter_review_cinema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cinema',
        ),
        migrations.AddField(
            model_name='review',
            name='cinema',
            field=models.ManyToManyField(to='collection.Cinema'),
        ),
    ]
