# Generated by Django 4.0.1 on 2022-01-14 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_remove_review_cinema_review_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='genres',
            field=models.ManyToManyField(to='collection.Genre'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='cinema',
        ),
        migrations.AddField(
            model_name='review',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collection.cinema'),
            preserve_default=False,
        ),
    ]
