# Generated by Django 4.0.1 on 2022-01-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_remove_review_cinema_review_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collection.review'),
            preserve_default=False,
        ),
    ]
