# Generated by Django 4.0.1 on 2022-01-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_movie_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review',
        ),
    ]
