# Generated by Django 4.0.1 on 2022-01-21 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_remove_movie_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collection.movie'),
            preserve_default=False,
        ),
    ]
